import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Sibebar from '@/components/sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className=" w-screen h-screen flex bg-slate-700">
    <Sibebar/>
    <div className=" pt-8 px-5 pr-8 w-full bg-background-normal">
        {children}
    </div>
</div>
  )
}
