import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Sibebar from '@/components/sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
<div className=" w-screen h-screen flex bg-slate-700">
  <div className=" top-0 left-0 w-64 bg-blue-800 overflow-y-auto">
    <Sibebar />
  </div>
  <div className="flex-col w-screen bg-white h-screen flex-1">
    {/* <div className="h-16 bg-gray-800"> </div> */}
    <div className="flex-1 mr-0 overflow-y-auto">
    <div className=" flex bg-slate-700">
  <div className="flex-col w-screen bg-white h-screen flex-1">
    <div className="h-16 bg-gray-800"> </div>
    <div className="flex-1 pt-8 mr-0 ">
      {children}
    </div>
  </div>
</div>    </div>
  </div>
</div>
  )
}
