import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Sibebar from '@/components/sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const tabElements = [
    {
        id: 'profile',
        name: 'profile',
        function: function(){},
    },
    {
        id: 'dashboard',
        name: 'dashboard',
        function: function(){},
    },
    {
        id: 'settings',
        name: 'setting',
        function: function(){},
    },
    {
        id: 'contacts',
        name: 'constrast',
        function: function(){},
    },
];
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
<div>
    <div>
      {children}
    </div>
</div>
  )
}
